# Publish all joint states from a joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10 # hz

# Control the wheels from a differential drive controller
# Also sets the hardware interface loop rate
diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['joint_front_left', 'joint_back_left']
  right_wheel: ['joint_front_right', 'joint_back_right']
  publish_rate: 10 # hz
  enable_odom_tf: false # encoder based, extremely unreliable
  pose_covariance_diagonal: [0.001, 0.001, 100000.0, 100000.0, 100000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 100000.0, 100000.0, 0.03]
  cmd_vel_timeout: 0.5 # seconds, will stop in case no cmd_vel received in 0.5s
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.2  # m/s
      min_velocity           : -0.2 # m/s
      has_acceleration_limits: false
      max_acceleration       : 1.0  # m/s^2
      min_acceleration       : -1.0 # m/s^2
      has_jerk_limits        : false
      max_jerk               : 2.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0  # rad/s
      has_acceleration_limits: false
      max_acceleration       : 2.0  # rad/s^2
      has_jerk_limits        : false
      max_jerk               : 4.0  # rad/s^3
