obstacle_range: 2.0
raytrace_range: 1.0
#footprint: [[0.1, 0.1], [-0.1, 0.1], [-0.1, -0.1], [0.1, -0.1]]
robot_radius: 0.15
inflation_radius: 0.5
#cost_scaling_factor: 10.0

#observation_sources: laser_scan_sensor point_cloud_sensor
#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
