global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
#  publish_frequency: 2.0
  static_map: true
#  plugins: 
#    - {name: static_layer, type: "costmap_2d::StaticLayer"}
#    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
#    - {name: obstacle,   type: "costmap_2d::ObstacleLayer"}
