local_costmap:
  global_frame: /odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.0625
#  plugins: 
#    - {name: static_layer, type: "costmap_2d::StaticLayer"}
#    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
#    - {name: obstacle,   type: "costmap_2d::ObstacleLayer"}

#  static:
#    map_topic: /atom/map
#    unknown_cost_value: -1
#    lethal_cost_threshold: 100

#  inflation_layer:
#    inflation_radius: 0.5
#    cost_scaling_factor: 10.0
